### ISSUE TITLE
Issue with source-location.

### ISSUE THREAD

**Issue by FiV0** [robert-strandh/Eclector#47]
When taking the README example with the following input:
```cl
(with-input-from-string (stream "1 ") ;; with an extra space
  (eclector.parse-result:read (make-instance 'my-client) stream))
```
the source-location of the 1 is considered to be the range (0 . 2) where I think it should be (0 . 1).
I think removing this [when](https://github.com/robert-strandh/Eclector/blob/master/code/reader/read-common.lisp#L151) might fix the issue, but I am not sure it serves another purpose.

**Comment by scymtym** [comment]
I have encountered this problem as well and have been thinking about solutions.

I don't think simply not consuming the whitespace is the right solution since that would make the behavior of `eclector.parse-result:read` different from `eclector.reader:read`.

A potential solution I have been experimenting with is calling `eclector.reader:read-preserving-whitespace` instead of `eclector.reader:read` from `eclector.parse-result:read`. This could maybe be followed up by consuming any tailing whitespace. If this works, it would not consider the trailing whitespace in the source location but still skip it before returning to the caller.
